### ISSUE TITLE
Visual Studio extension fails to show transformation for JSON files that are not build configurations

### ISSUE THREAD

**Issue by paulomorgado** [Microsoft/slow-cheetah#101]
I have this transformations:

    config.json
        config.Debug.json
        config.PublishDebug.json
        config.PublishRelease.json
        config.Release.json

The extension successfully shows the result of the transformation for `config.Debug.json` and `config.Release.json` but doesn't even launch the diff viewer for `config.PublishDebug.json` and `config.PublishRelease.json
`.

**Comment by davilimap** [comment]
Does the Preview Transform option show up for all the files?

**Comment by davilimap** [comment]
This specific problem is the same as #98, so I'll close this issue in favor of that. I think there's also an issue with Publish profiles being considered in Add and Preview Transform. I'll open another issue for that.
