### ISSUE TITLE
Json transformation loses data

### ISSUE THREAD

**Issue by artmdv** [Microsoft/slow-cheetah#107]
Trying to replace whole file which contains date with zero'es as milliseconds results in transformed file losing those zero'es

Transformation file:
`{
    "value": "2017-12-20T20:10:00.0000000"
}`

Transformed file:
`{
    "value": "2017-12-20T20:10:00"
}`

Expected transformed file:
`{
    "value": "2017-12-20T20:10:00.0000000"
}`

**Comment by davilimap** [comment]
This would be a problem with [JDT,](https://github.com/Microsoft/json-document-transforms) the JSON trasnformation engine that SlowCheetah uses. I'll reopen this issue over there.
