### ISSUE TITLE
.net standard 2.0

### ISSUE THREAD

**Issue by JamesItSolutionsLtd** [Microsoft/slow-cheetah#137]
Struggling to get this to work with a .net standard 2 project.

Nuget package fails to install

Some background:
I have a xamarin solution and using an app.config with transforms to define web api url based on the config used.
This is hand coded but doesn't work on visual studio for mac because of web.publishing....dll not present in the same location as on windows

was hoping to use slowcheetah in a CI like setup with the neccessary files as part of the solution.

**Comment by davilimap** [comment]
Does the SlowCheetah Nuget package fail to install on the project? What is the output from the Package Manager? I tried with a new .NET Standard library and was able to install the nuget package.

**Comment by JamesItSolutionsLtd** [comment]
Hi
It appears it was an issue with my SDK style project file.

Not sure what it was but rebuilt the project and all is ok.
