### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by biltongza** [Microsoft/slow-cheetah#138]
At the bottom of https://github.com/Microsoft/slow-cheetah/blob/master/doc/update.md there is a link to #209, which seems to point to a page that doesn't exist (https://github.com/sayedihashimi/slow-cheetah/issues/209).

Where is the issue that is tracking the auto migration of old SlowCheetah packages? There doesn't appear to be an issue #209 in this repo.

**Comment by davilimap** [comment]
Seems like the old SlowCheetah repo had Issues turned off/removed. I'll update the docs to remove these dead links
