### ISSUE TITLE
When publishing a .Net Core console app, no transformation is applied

### ISSUE THREAD

**Issue by advapiIT** [Microsoft/slow-cheetah#139]
[Slowcheeta.zip](https://github.com/Microsoft/slow-cheetah/files/2163031/Slowcheeta.zip)
Hello,
I've created a simple project I've attached to demonstrate what happens.
I have a publish profile that sets the build profile as release

I've got 3 different appsettings.json

One for Debug that has a value "Test" : "Debug 
One for Release that has a value "Test" : "Releeeeaseee!
One for FolderProfile (the publish profile) that has a value "Test" : Testt1234!

Now when I publish with FolderProfile I see as output "Debug" . At least I was pointing at Release since the publish profile is release. (Even if I was betting on Test1234!

I'm trying with latest version of SlowCheeta 

Thanks

**Comment by advapiIT** [comment]
any update on this?

**Comment by davilimap** [comment]
The publishing pipeline for .NET Core is fundamentally different than the one for .NET Framework (what SlowCheetah was designed for). We're currently tracking support for .NET Core publishing in #7.

Closing this issue in favor of #7.
