### ISSUE TITLE
Replacing with values read from file or generated from code?

### ISSUE THREAD

**Issue by jez9999** [Microsoft/slow-cheetah#140]
I would like to transform some elements of my config file not with hard-coded values in a transform file, but either with the contents of another file or (preferably) a value generated from code.  For example, in the case of generating a value from code, instead of this:

```
{
    "someSettings": {
        "@jdt.replace": {
            "timeTokenAtBuild": "1f3ac2"
        }
    }
}
```

... I want something like this:
```
{
    "someSettings": {
        "@jdt.replace": {
            "timeTokenAtBuild": [MyUtilitiesLibrary.GetCurrentTimeToken()]
        }
    }
}
```

Getting the value from something like a PowerShell script would be fine too.  Can I do this with SlowCheetah currently?  If not how hard would it be to extend it to allow this functionality?

**Comment by davilimap** [comment]
This would be an additional feature for [JDT](https://github.com/Microsoft/json-document-transforms), the transformation engine SlowCheetah uses for transforming JSON files. I'll open an issue there.

**Comment by jez9999** [comment]
@davilimap By the way, what is the equivalent engine SlowCheetah uses for transforming XML files?  I'd like to submit an issue there, too.
