### ISSUE TITLE
Update Link in readme.txt

### ISSUE THREAD

**Issue by TheMrAnderson** [Microsoft/slow-cheetah#141]
The link in the readme is invalid.  https://marketplace.visualstudio.com/items?itemName=WillBuikMSFT.SlowCheetah-XMLTransforms returns a 404

**Comment by davilimap** [comment]
Can you please link the readme file that contains this link. Both [transforming_files.md](https://github.com/Microsoft/slow-cheetah/blob/master/doc/transforming_files.md) and [readme.txt](https://github.com/Microsoft/slow-cheetah/blob/master/src/Microsoft.VisualStudio.SlowCheetah/Build/readme.txt) have the correct link at the moment

**Comment by TheMrAnderson** [comment]
When the NuGet package 3.0.61 (Published May 11, 2017) which is the latest NuGet package, the readme.txt that pops up after installation has the bad link.  If I clone this repo and install the latest build, the link is updated.  It would be great to have a new NuGet package published, but that's #142

**Comment by davilimap** [comment]
A new version will be published soon. For now, there is the preview version (3.1.61-pre)
