### ISSUE TITLE
Format XML while transforming (or keep whats there)

### ISSUE THREAD

**Issue by TiltonJH** [Microsoft/slow-cheetah#144]
Since version v3.1.66 it seems that the entire XML file is reformatted, while earlier version only reformatted the changed sections of the file.

This results in two issues for me.

First of all the preview in VS shows way more changes than were actually made by SlowCheetah. Which in turn make the preview very confusing.

And second all of my indented XML format for the output file is gone.

Is there a way to tell SlowCheetah how to format the file?
Or may be revert this new effect?

#### My intended XML format pattern (example):
(Write the first attribute on the line of the tag and every other attribute on the next line. Uses tabs (4 spaces wide) and spaces to align the attributes. (Is one of the possible XML format settings in VS))
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	[...]
	<system.serviceModel>
	[...]
		<client>
			<endpoint address="[...]"
					  binding="[...]"
					  bindingConfiguration="[...]"
					  behaviorConfiguration="[...]"
					  contract="[...]" />
		</client>
	[...]
	</system.serviceModel>
	[...]
</configuration>
```

#### The patterns of SlowCheetah:
(Write attributes on the line of the tag and a new line after it exceeds a certain length (?). Intend uses tabs (? spaces wide) to align the attributes.)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	[...]
	<system.serviceModel>
	[...]
		<client>
			<endpoint address="[...]" binding="[...]" bindingConfiguration="[...]"
				behaviorConfiguration="[...]" contract="[...]"/>
		</client>
	[...]
	</system.serviceModel>
	[...]
</configuration>
```

**Comment by steeevec** [comment]
We're also seeing this. Of particular annoyance is the removal of the space before closing slash `/>`. When previewing a transform in Visual Studio, it now appears the majority of the file has changed.

**Comment by davilimap** [comment]
Thanks for reporting this. It seems to be an issue with `System.Xml.XmlTextReader` not preserving the formatting of the file being read. We switched to this a while back to better control how the source file was read. I'll look into a fix

**Comment by davilimap** [comment]
Version 3.1.69 of the extension should fix this. Reopen in case the problem persists.

**Comment by TiltonJH** [comment]
Great news! Thx! :-)

I'll give it a spin, once it has been released.

**Comment by TiltonJH** [comment]
I can confirm that version 3.1.69 of the .vsix fixes the VS preview part of the issue.

Great Work! Thx!

**Comment by cell001uk** [comment]
I have 3.1.69.25612 and this is still happening.  Removes spaces before the /> and inlines all of my nicely formatted attributes.  I have latest addin and nuget packages, and all VS updates applied.  Any idea what's going on?

**Comment by Andy9FromSpace** [comment]
@cell001uk I had the same issues like you, but only in web application projects. In those, I had the "Preview transform" item in the context menu even without installing the SlowCheetah nuget for this project. But the preview had the issues you mentioned.

After I installed the SlowCheeta nuget in the web application project and added ```<IsTransformFile>True</IsTransformFile>``` to the transform file elements in the csproj, I ended up with two "Preview transform" items in the context menu. And the new one worked the same way as for library projects.

![image](https://user-images.githubusercontent.com/8110440/55961383-141bc400-5c6f-11e9-8343-fd70700d639b.png)

The "Preview transform" at the top doesn't reformat the xml, but the other one does.

**Comment by TiltonJH** [comment]
@cell001uk and @Andy9FromSpace 
Hi, IMHO, I think that your comments are a little of topic and need each a different issue.

@cell001uk 
In my initial comment I wrote:
> Since version v3.1.66 it seems that the entire XML file is reformatted, **while earlier version only reformatted the changed sections of the file.**

It has always been the way for the XML transformation to lose the format within the transformed sections. I don't see how this could be fixed other than telling the transformation system what format is being used or have some kind of detector code which can determine the used format. Which (IMHO) is a new feature entirely and not really part of the issue I had.
However, I would love to see such a feature in the future. :-)
