### ISSUE TITLE
Build fails for projects which reference Microsoft.Azure.DocumentDB and latest SlowCheetah

### ISSUE THREAD

**Issue by AdnanSoftic** [Microsoft/slow-cheetah#147]
Hi,

I have a Web API  project which is referencing Microsoft.Azure.DocumentDB nuget package and latest version of Microsoft.VisualStudio.SlowCheetah - 3.1.66.

When building the project following error message is displayed:
The item "c:\users\****\source\repos\SlowCheetah.Transformations\packages\Microsoft.Azure.DocumentDB.1.22.0\build\..\runtimes\win7-x64\native\Microsoft.Azure.Documents.ServiceInterop.dll" in item list "ContentWithTargetPath" does not define a value for metadata "TransformOnBuild".  In order to use this metadata, either qualify it by specifying %(ContentWithTargetPath.TransformOnBuild), or ensure that all items in this list define a value for this metadata.	SlowCheetah.Transformations	.

This does not occur when using version: 3.0.61 of Microsoft.VisualStudio.SlowCheetah

**Comment by davilimap** [comment]
Thanks for pointing this out. I think I have an idea on why this is happening, I'll look into it.

**Comment by bording** [comment]
@davilimap It looks like this problem is happening because of the changes introduced in #119.

In that PR, additional `ItemGroup`s are being checked for the `TransformOnBuild` item metadata, but the `ItemDefinitionGroup` wasn't updated to add that metadata.

Looks like adding `_NoneWithTargetPath` and `ContentWithTargetPath` to the `ItemGroupDefinition` that adds the `TransformOnBuild` metadata would fix this problem.

**Comment by genwex** [comment]
could you please be a little more specific? are you making this change or can advice on where to make this change?

**Comment by JimHume** [comment]
I've been hitting this issue quite a lot. Has there been any progress on this issue?

**Comment by kgar** [comment]
I've been having this problem as well, but with _NoneWithTargetPath:
\packages\Microsoft.VisualStudio.SlowCheetah.3.1.66\build\Microsoft.VisualStudio.SlowCheetah.targets(68,5): error MSB4096: The item in item list "_NoneWithTargetPath" does not define a value for metadata "TransformOnBuild".  In order to use this metadata, either qualify it by specifying %(_NoneWithTargetPath.TransformOnBuild), or ensure that all items in this list define a value for this metadata.

**Comment by bording** [comment]
@genwex I was just about to post the same thing!

Using that should get things working until Microsoft puts out an updated version with a fix.

**Comment by genwex** [comment]
or, redo this again if they release a new version without this fix. :)

**Comment by bording** [comment]
@genwex Instead, I'd suggest adding your workaround `ItemDefinitionGroup` to your csproj file instead of editing the slowcheetah file.

**Comment by genwex** [comment]
very good point too! thanks for that!

**Comment by kgar** [comment]
> @genwex Instead, I'd suggest adding your workaround `ItemDefinitionGroup` to your csproj file instead of editing the slowcheetah file.

That's perfect. Thank you so much! I don't know nearly as much as I should about how metadata works in projects and targets files... Is there somewhere I can go to get a better idea of how they work?

**Comment by lonevvolf** [comment]
Is there a reason this is not yet resolved?  We have hundreds of projects, and editing each csproj to workaround it is quite a pain.

**Comment by dyslexicanaboko** [comment]
Just throwing my two cents in here:
- I encountered this problem only after upgrading to the latest version of Slow Cheeta.
- I attempted to add the suggested code above to the `Microsoft.VisualStudio.SlowCheetah.targets` file and it didn't work.
- I took @bording's suggestion and instead added it to my csproj, this worked.
- This is not ideal at all especially on the day of a deployment, but I guess that's beating a dead horse.

I just wanted to summarize the above thread into:
1. Edit your affected *.csproj file (In VS or with a text editor)
1. Add the following XML below to the bottom of your file inside of your `<Project>` tags:
  1. If you already have a `<ItemDefinitionGroup>` declared, then add the contents to that tag instead.
```
<ItemDefinitionGroup>
    <!-- Default TransformOnBuild values for file types -->
    <_NoneWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </_NoneWithTargetPath>
    <ContentWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </ContentWithTargetPath>
</ItemDefinitionGroup>
```

**Comment by skowronek** [comment]
> Just throwing my two cents in here:
> 
> * I encountered this problem only after upgrading to the latest version of Slow Cheetah.
> * I attempted to add the suggested code above to the `Microsoft.VisualStudio.SlowCheetah.targets` file and it didn't work.
> * I took @bording's suggestion and instead added it to my csproj, this worked.
> * This is not ideal at all especially on the day of a deployment, but I guess that's beating a dead horse.
> 
> I just wanted to summarize the above thread into:
> 
> 1. Edit your affected *.csproj file (In VS or with a text editor)
> 2. Add the following XML below to the bottom of your file inside of your `<Project>` tags:
> 3. If you already have a `<ItemDefinitionGroup>` declared, then add the contents to that tag instead.
> 
> ```
> <ItemDefinitionGroup>
>     
>     <_NoneWithTargetPath>
>       <TransformOnBuild>false</TransformOnBuild>
>     </_NoneWithTargetPath>
>     <ContentWithTargetPath>
>       <TransformOnBuild>false</TransformOnBuild>
>     </ContentWithTargetPath>
> </ItemDefinitionGroup>
> ```

Sometimes, you just have to break things to see what's in them...

This fixed my project as well. Would not recommend editing the target file as mentioned above.

**Comment by HNeukermans** [comment]
Downgraded Microsoft.VisualStudio.SlowCheetah to version 3.0.56 fixed my problem :-)

**Comment by davilimap** [comment]
Thanks for all your help in identifying the issue and the fix. Sorry for the delay in implementing this. It will be released shortly in version 3.2 with VS 2019 compatibility was well.

Fixed by #171

**Comment by xantari** [comment]
I think this might need to be reopened. I'm also having this error in 3.2.20 slowcheetah and VS 2019 (16.0.0 and also occurred on 16.0.3).

The only fix was to add the following lines to the affected .csproj:

```
  <ItemDefinitionGroup>
    <!-- Default TransformOnBuild values for file types -->
    <_NoneWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </_NoneWithTargetPath>
    <ContentWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </ContentWithTargetPath>
  </ItemDefinitionGroup>
```
![image](https://user-images.githubusercontent.com/6610039/57147093-6b074b80-6d8c-11e9-8fcc-1a22e43c195d.png)

65>C:\TFS\ARRT.All.Projects\packages\Microsoft.VisualStudio.SlowCheetah.3.2.20\build\Microsoft.VisualStudio.SlowCheetah.App.targets(54,5): error MSB3023: No destination specified for Copy. Please supply either "DestinationFiles" or "DestinationFolder".

It could be that the fix provided in this posting doesn't work with linked files that need to be transformed on build?

For instance if you have this in a class library called Logging:

```
<None Include="SEQ.config">
      <TransformOnBuild>true</TransformOnBuild>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="SEQ.Debug.config">
      <DependentUpon>SEQ.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="SEQ.DebugProd.config">
      <DependentUpon>SEQ.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="SEQ.Impersonation.config">
      <DependentUpon>SEQ.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="SEQ.InternalRelease.config">
      <DependentUpon>SEQ.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="SEQ.Release.config">
      <DependentUpon>SEQ.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
    <None Include="SEQ.Staging.config">
      <DependentUpon>SEQ.config</DependentUpon>
      <IsTransformFile>true</IsTransformFile>
    </None>
  </ItemGroup>
```

Then in another project you have a link to that file such as this in your .csproj:

```
    <None Include="..\Logging\SEQ.config">
      <Link>SEQ.config</Link>
    </None>
```

**Comment by peheje** [comment]
I had the issue using Microsoft.VisualStudio.SlowCheetah 3.0.61, I upgraded to 3.2.26 and it builds.

**Comment by nbadal263** [comment]
> @genwex Instead, I'd suggest adding your workaround `ItemDefinitionGroup` to your csproj file instead of editing the slowcheetah file.

Adding this to the .csproj file solved this issue for me

<ItemDefinitionGroup>
    
    <_NoneWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </_NoneWithTargetPath>
    <ContentWithTargetPath>
      <TransformOnBuild>false</TransformOnBuild>
    </ContentWithTargetPath>
</ItemDefinitionGroup>
