### ISSUE TITLE
Not working under VS2017

### ISSUE THREAD

**Issue by mwpowellhtx** [Microsoft/slow-cheetah#151]
I am trying to use SlowCheetah under VS2017, but it does not seem to be working. I added the package reference, but I do not see any context menus when I right click the content item. Admittedly, the content item is a ``.targets`` file, which is still Xml, right, but is not an ``.xml`` or ``.config`` file extension, but it is still very much Xml within. Even after adding an ``App.config``, let's say, I still do not see any context menus that I remember seeing before. I test under VS2015, and definitely the *Add Transform* menu option is there. Just not under VS2017. Any chance for an update under VS2017 please? Thanks!

**Comment by mwpowellhtx** [comment]
I saw some other comments, differences between NuGet installed behavior versus VSIX installed behavior. I suppose this is a duplicate of those reports, but I cannot verify the VSIX aspect at the moment on account of VS marketplace being completely down at the moment, website, package store, etc. Does anyone happen to have a copy of the VSIX handy that I could download apart from the marketplace sources? Thanks!

**Comment by davilimap** [comment]
You are correct, the VSIX is what adds context menus and the logic behind the commands. See #153 for getting the .vsix file.
