### ISSUE TITLE
Add version(s) for the packages/VSIX

### ISSUE THREAD

**Issue by mwpowellhtx** [Microsoft/slow-cheetah#152]
It would be real handy to know which version(s) of SlowCheetah have been installed.

**Comment by davilimap** [comment]
You can see the VSIX extension version by going to `Tools > Extensions and Updates` in Visual Studio. If SlowCheetah is installed, you can see the version by clicking on it in the main menu.
You can see the nuget package version installed in Visual Studio by right-clicking the project or solution, selecting **Manage Nuget Packages** then finding SlowCheetah, if it's installed.
