### ISSUE TITLE
VSIX build not apparently working in VS2017

### ISSUE THREAD

**Issue by mwpowellhtx** [Microsoft/slow-cheetah#153]
Is there anything in particular I need to do in order for the VSIX to build working from VS2017? In the absence of the marketplace, until that is resolved, I cloned the source, and am trying to rebuild the VSIX to my local. But I do not seem to be finding anything land in the ``bin`` folder.

**Comment by davilimap** [comment]
You can go [here](https://github.com/Microsoft/slow-cheetah/releases) to download any previously released versions.

**Comment by mwpowellhtx** [comment]
@davilimap Awesome, thanks for pointing that out!
