### ISSUE TITLE
Really confusing multiple NuGet packages

### ISSUE THREAD

**Issue by jez9999** [Microsoft/slow-cheetah#165]
So I've been looking at the SlowCheetah documentation and the NuGet packages now for a while and I'm just confused.  As far as I can tell there are 4 separate things:

1. SlowCheetah VSIX extension
2. SlowCheetah NuGet package
3. SlowCheetah.Xdt NuGet package
4. Microsoft.VisualStudio.SlowCheetah NuGet package

I understand that you install 1) to add the GUI to Visual Studio, and it then installs 4) to do transforms in Visual Studio.  What I don't understand is the purpose of 2) and 3).

Please could someone explain clearly what these 4 different things are for, and I think this explanation should be added to the documentation on this repo because it's really unclear.

**Comment by davilimap** [comment]
The SlowCheetah VSIX extension (item 1) provides support for adding and previewing transform files. It also installs the SlowCheetah Nuget package (item 4) which is necessary for build-time transformations. See [this](https://github.com/Microsoft/slow-cheetah/blob/master/doc/transforming_files.md) for more info on that.
Item 2 is the old version of the SC Nuget package, which is not supported by Microsoft. Item 3 is a Nuget package containing XDT, the engine behind the XML transforms that SlowCheetah performs. Neither of these are published or supported by Microsoft, look for that when downloading SlowCheetah assets.
