### ISSUE TITLE
SlowCheetah removes blank lines

### ISSUE THREAD

**Issue by jez9999** [microsoft/slow-cheetah#167]
Sometimes I like to have blank lines in my XML files to make them look nicer.  When I replace a section using XDT with SlowCheetah, it removes blank lines.  Is there a way I can get it to leave them in?

**Comment by davilimap** [comment]
This is a known error with XDT as it does not provide a way to preserve new lines, despite having an option to preserve whitespace. Unfortunately, there is nothing SlowCheetah can do to prevent this.
