### ISSUE TITLE
name's story

### ISSUE THREAD

**Issue by odrix** [Microsoft/slow-cheetah#172]
Hello, 

Thanks for this great plugin. But I'm curious : Why this name ? What is his story or meaning or reference ?
I'm very intrigued ?

Thanks for the answer

**Comment by Thieum** [comment]
[Slow Cheetah](https://en.wikipedia.org/wiki/Slow_Cheetah) is a song by The Red Hot Chili Peppers and the original author @sayedihashimi[ confirmed being a Red Hot Chili Peppers fan](https://codeclosure.wordpress.com/2012/11/15/using-slowcheetah-to-transform-any-config-file-based-on-publish-profiles-and-save-us-for-config-hell/)

![image](https://user-images.githubusercontent.com/944894/51271673-2e0e7900-1996-11e9-9cc4-51b312fe8f2d.png)

**Comment by davilimap** [comment]
Interesting! Thanks for the answer
