### ISSUE TITLE
3.2 not available on Nuget yet

### ISSUE THREAD

**Issue by PhilPJL** [Microsoft/slow-cheetah#178]
When are you going to push the new version up?

**Comment by johanbenschop** [comment]
We're also waiting for this update with some anticipation. Its been 13 days since release on GitHub and still not on NuGet :(

**Comment by davilimap** [comment]
Sorry for the delay on this. We ran into some issues with our internal nuget publishing services, but the Nuget package should be out. Note that this is versions 3.2.20, because of a minor fix that had to be put in for publishing, but it should contain all of the latest features and fixes.
