### ISSUE TITLE
Support for custom config files?

### ISSUE THREAD

**Issue by Fluttercom** [microsoft/slow-cheetah#179]
Hi,
I created a custom configsection file TestSection.config:
`<TestSection configSource="TestSection.config" />`
I've added transformation to it, but it doesn't work.
Is it not supported? Or I missed something?

**Comment by davilimap** [comment]
Do you have any more context on this? What do the files look like?

Try to test this transformation here and see if it works: https://webconfigtransformationtester.apphb.com/

**Comment by Fluttercom** [comment]
Nevermind, I solved the issue another way.
