### ISSUE TITLE
suport for bundleconfig.json file

### ISSUE THREAD

**Issue by GathisB** [microsoft/slow-cheetah#181]
slow-cheetah not support this json format
```
[
  {
    "outputFileName": "bbb.min.js",
    "inputFiles": [
      "bbb.js"
    ],
    "minify": {
      "enabled": true
    }
  },
  {
    "outputFileName": "ccc.min.js",
    "inputFiles": [
      "ccc.js"
    ],
    "minify": {
      "enabled": true
    }
  }
]
```

`Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.`

**Comment by davilimap** [comment]
SlowCheetah uses [JDT](https://github.com/microsoft/json-document-transforms) which currently does not support root level arrays. You can open a bug there to request this functionality.
