### ISSUE TITLE
Why can't I add all my build configs?

### ISSUE THREAD

**Issue by natiki** [microsoft/slow-cheetah#186]
Hi,

- Slow Cheetah NuGet: 3.2.20, Extension 3.2.18.4433

I have a number of build configs but SC only allows me to install Local, Debug and Release. Why will it not add the others when I click on `Add Transform`?

![image](https://user-images.githubusercontent.com/4738140/55774633-4eebf380-5ad9-11e9-80b0-5ada1a510afc.png)

**Comment by Kluez** [comment]
I had the issue, that the **solution** profiles did not match the **project** configuration. I guess if you check your project-properties, and check section 'build' and there the drop-down - you only see Debug, Local and Release.

Change your project setup to include those build configurations, then let it generate again..
