### ISSUE TITLE
Transformation does not work

### ISSUE THREAD

**Issue by camerontbelt** [microsoft/slow-cheetah#197]
I followed the guide from here 

[Guide](https://marketplace.visualstudio.com/items?itemName=vscps.SlowCheetah-XMLTransforms)

I click on preview transform and I just get the app.config file without any changes from the App.Debug.config. 

Using Visual Studio 2019 version 16.2.0 preview 3.0 with latest nuget and extension.

**Comment by mikehac** [comment]
Hello,
It also happened to me. 
Beside that, the url http://schemas.microsoft.com/XML-Document-Transform which should be added to xmlns:sdt of configuration node of app.config, it returns "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." when I try to reach it in browser

**Comment by Austin-WXJ** [comment]
Hi,

Wanted to add to the discussion that I've discovered this issues is affecting my teams project as well. We have several non-web projects in our solution with several transformations for each. 

We're using VS 2017 with the MS SlowCheetah Extension installed. 

I've spent time troubleshooting this by creating a simple .NET 4.6.2 Framework Console App, adding a new configuration, "transform", to the Configuration Manager, right clicking on the app.config and added transformations where app.debug.config, app.release.config and app.transform.config appear nested below app.config. Then made an appSettings and connectionStrings area for transformation.

I've tried every version of MS.VS.SlowCheetah  available, including v.2.5.48, from Nuget Package Manager to no avail. 

finally to add, our web projects' web.configs transform just fine.

below are the test project app.config,
```
<!--app.config-->
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings>
    <add name="DataConnectionString" connectionString="Data Source=ReplaceThis;Initial Catalog=ReplaceMe;Integrated Security=true" providerName="System.Data.SqlClient" />
  </connectionStrings>
  <appSettings>
    <add key="Environment" value="DEV" />
  </appSettings>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
    </startup>
</configuration>
```

```
<!--app.transform.config-->
<?xml version="1.0" encoding="utf-8"?>
<!--For more information on using transformations see the web.config examples at http://go.microsoft.com/fwlink/?LinkId=214134. -->
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <connectionStrings>
    <add name="DataConnectionString" connectionString="Data Source=ThisisReplaced;Initial Catalog=Iamreplaced;Integrated Security=true" providerName="System.Data.SqlClient"  xdt:Transform="Replace" xdt:Locator="Match(name)"/>
  </connectionStrings>
  <appSettings>
    <add key="Environment" value="LOCAL" xdt:Locator="Match(key)" xdt:Transform="SetAttributes"/>
  </appSettings>
</configuration>
```

```
<!--packages.config-->
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.VisualStudio.SlowCheetah" version="3.2.20" targetFramework="net462" developmentDependency="true" />
</packages>
```

**Comment by davilimap** [comment]
This issue is probably related to #169, which was an unintended breaking change. This will be reverted and a new version will be released soon. The schema URL should not affect the occurrence of the transforms.
