### ISSUE TITLE
Error installing SlowCheetah package

### ISSUE THREAD

**Issue by hleerobinson** [microsoft/slow-cheetah#202]
I am receiving this message in Visual Studio: 
Installing SlowCheetah NuGet package to PAY530 ...
Error installing SlowCheetah NuGet package to PAY530.
How can I get more detail?  Why is it installing the package into my project?

**Comment by davilimap** [comment]
What type of project is this?

Can you try manually installing the package to your project (PAY530)? Right-click, manage nuget packages, search for Slow Cheetah.

**Comment by hleerobinson** [comment]
It says "No Packages Found" no matter which Package Source I select.  There must be something I am not understanding about NuGet packages.

**Comment by hleerobinson** [comment]
I have the same behavior with Visual Basic and with Visual COBOL projects.

**Comment by davilimap** [comment]
I can't reproduce this issue by creating a new VB project. The SlowCheetah package shows up as expected. Make sure you have the Nuget package source selected (the source URL should be https://api.nuget.org/v3/index.json)

**Comment by hleerobinson** [comment]
In the NuGet Package manager, I added the URL to my list Package Sources.  I did a Browse and search for "Slow" and found four items with "SlowCheetah".  I downloaded and installed Microsoft.VisualStudio.SlowCheetah.  In the Package Manager Console, when I enter get-package, it shows as installed, "Microsoft.VisualStudio.SlowCheetah {3.2.20}"  Now when I right-click on "app.config" then click on "Add Transform" the "Do you want to install...?" message does not appear.  Nothing else happens either.  No error message, no dialog box, no "app.*" file.  Nothing.

If I open another solution, I again get the "Install SlowCheetah NuGet package" dialog box.

**Comment by hleerobinson** [comment]
It appears to be working in the second solution now.
