### ISSUE TITLE
VS 2022 support?

### ISSUE THREAD

**Issue by MikeJansen** [microsoft/slow-cheetah#229]
Will SlowCheetah be updated for VS2022 or better yet, integrated into 2022 before RTM?

**Comment by ImGonaRot** [comment]
This issue is tied to pull request [233](https://github.com/microsoft/slow-cheetah/pull/233)

**Comment by adrianvmsft** [comment]
A version compatible with VS 2022 has been published to the Visual Studio Marketplace.
