### ISSUE TITLE
VS2022 Error while loading solution

### ISSUE THREAD

**Issue by Kydyralin** [microsoft/slow-cheetah#279]
Hello everyone,

IDE: Microsoft Visual Studio 2022 version: 17.0.32803.143
OS: Windows 11 Pro 22H2

Today I started to face an issue which I could not solve by myself. For some reason SlowCheetah started to fail loading when I open solution.
![image](https://github.com/microsoft/slow-cheetah/assets/22542620/e0f3a230-1ff1-421e-9c92-83cf5963aa56)
In the activity log file I found following error regarding SlowCheetah load:

```html
<entry>
    <record>554</record>
    <time>2023/06/02 10:30:49.694</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [SlowCheetahPackage]Source: &apos;Microsoft.VisualStudio.SlowCheetah.VS&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at Microsoft.VisualStudio.SlowCheetah.VS.BaseCommand.RegisterCommandAsync()&#x000D;&#x000A;   at Microsoft.VisualStudio.SlowCheetah.VS.SlowCheetahPackage.&lt;InitializeAsync&gt;d__34.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{9EB9F150-FCC9-4DB8-9E97-6AEF2011017C}</guid>
    <hr>0x80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
```

It seems like it lookups for Microsoft.VisualStudio.Threading but I do not really understand why it needs that assemble and why it was working fine so far.

Any ideas on this problem?

**Comment by RobertSchoen** [comment]
I am also having this issue.    I am running Windows 10 Pro 22H2.

**Comment by FixRM** [comment]
+1

**Comment by FixRM** [comment]
@ttstanley, can you please look at this issue? May be, somebody can help with previous version download link?

**Comment by KernelLeak** [comment]
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscps/vsextensions/SlowCheetah-XMLTransforms-VS2022/4.0.12.36915/vspackage worked for me.

**Comment by FixRM** [comment]
@KernelLeak thanks. How did you get link for previous version?

**Comment by KernelLeak** [comment]
I had the old version still installed on another machine, so I took the current download link from the marketplace and just changed the version number in it... :)

**Comment by ttstanley** [comment]
Does the extension work if you update your version of visual studio to the latest?

**Comment by RobertSchoen** [comment]
I was on version 17.3.6 and now I am on 17.6.2.    I am no longer getting the error.   The only thing I have now is in the Options/Slow Cheeta/Advanced.   It is showing "An error occurred loading this property page".    I don't know if that is related or how it behaved before my issues started.

Thank you for your help with this.

**Comment by FixRM** [comment]
> Does the extension work if you update your version of visual studio to the latest?

No, I'm always running the latest VS version

**Comment by KernelLeak** [comment]
I'm still waiting for the first "big" update to 17.6, so I'm still on 17.5...

**Comment by dwainew** [comment]
I'm getting it on VS 17.5.4

**Comment by timammons** [comment]
I'm getting the same error with:

IDE: Microsoft Visual Studio 2022 version: 17.1.3
OS: Windows 10 Pro 22H2

**Comment by ttstanley** [comment]
There has been an update for the extension that was just released with a potential fix. Try updating the Slowcheetah extension and see if it now works.

**Comment by FixRM** [comment]
Looks good! Thanks @ttstanley
