### ISSUE TITLE
slow-cheetah AWS toolkit problems?

### ISSUE THREAD

**Issue by linusnikander** [Microsoft/slow-cheetah#31]
Are there any known issues with slow-cheetah and AWS toolkit in VS2017? The reason I'm asking is because I'm having trouble updating AWS instances and the trouble started after I installed and started using slow-cheetah.

In addition to this, whilst searching for people with a similar problem I came across this post
https://forums.aws.amazon.com/thread.jspa?threadID=219034 which is exactly the problem I'm having. (the search term "Could not move C:\cfn\download_version_bundle.ps1.bak2 to C:\cfn\download_version_bundle.ps1.bak" led me there, this was the only good hit). 

The link above doesn't explicitly mention slow-cheetah but since the author of the post is Sidney Haddad I thought it might be more than coincidence?

**Comment by davilimap** [comment]
Not sure what you mean with the post, but that seems to be a different problem.
Can you describe more about the problem you are having? Do you have the build logs from AWS?

**Comment by jviau** [comment]
Closing for now, does not appear to be slow-cheetah related. Please re-open if you need more assistance.
