### ISSUE TITLE
Visual Studio 2017 extension not available for download 

### ISSUE THREAD

**Issue by b-rewired** [Microsoft/slow-cheetah#39]
The link in the transforming_files.md links to the SlowCheetah Visual Studio extension but it's a 404.
https://marketplace.visualstudio.com/items?itemName=WillBuikMSFT.SlowCheetah-XMLTransforms

If you google the itemName it links to the same page above but the tool is not available.

I'm looking at the installed Extensions and Updates in my VS2017 and the nuget package definitely didn't install the extension - this is coupled by the fact that I can't transform a simple .config file.

**Comment by applyThoughts** [comment]
Yes the link does not work for me as well . However the package is still available from this page that works for 2017. 
[Extension Link](https://github.com/sayedihashimi/slow-cheetah/releases)
I was able to download the vsix from the releases and install it. No issues.

**Comment by davilimap** [comment]
The page should be working now. Also, the relase notes for the latest release can be found [here](https://github.com/Microsoft/slow-cheetah/releases/tag/v3.0.61).
