### ISSUE TITLE
Add Config Transform no longer available on all files

### ISSUE THREAD

**Issue by nlaslett** [Microsoft/slow-cheetah#41]
Our site uses a web.config.template file with config-specific transforms.  Under the previous version (2.5.48) this was not a problem and we could add/update transform files with the right-click Add Config Transform.

`<TransformXml Source="Web.config.Template" Destination="Web.config" Transform="Web.config.$(Configuration).template" />`

Under the current version 3.0.61 the Add Config Transform option is not available on our .template files (although Preview Transform still works).  I'm also unable to manually add or rename transform files via Solution Explorer.  I want to avoid manually editing the project file if possible.

Is this now an unsupported setup?  I believe it was put in place to allow transforms to happen on build (in the working directory) and not just on publish.  The generated web.config is, of course, not included in source control.

**Comment by davilimap** [comment]
I tried to reproduce this by creating a new web project and adding a file called `Web.config.Template` but I was able to add transforms as normal (as shown below). Can you give me some steps to reproduce this issue from a new project?
![image](https://cloud.githubusercontent.com/assets/11531010/26070583/f625fe0a-3959-11e7-84bf-00fa1cb4e467.png)
Not being able to edit files in the solution explorer seems to be another issue, probably with Visual Studio itself. SlowCheetah just adds the files to the project as children of the original file.

**Comment by nlaslett** [comment]
Well damn.  I was able to successfully set things up in a new project, including the build trigger, and SlowCheetah 3.0.61 is just working fine.  I'm able to add and update the transforms with the right click.  This was either user error or a specific problem in my project.  Apologies and thanks for looking into it so quickly.
