### ISSUE TITLE
Compatibility with VS 2013

### ISSUE THREAD

**Issue by MassimoSporchia** [Microsoft/slow-cheetah#45]
as the title says, I'm not able to install the official extension package distrbution on VS 2013, attached log:
```
9/2017 5:31:25 PM - Searching for applicable products...
5/19/2017 5:31:25 PM - Found installed product - Microsoft Visual Studio Premium 2013
5/19/2017 5:31:25 PM - Found installed product - Microsoft Visual Studio Professional 2013
5/19/2017 5:31:25 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
5/19/2017 5:31:25 PM - Found installed product - Global Location
5/19/2017 5:31:25 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```

**Comment by davilimap** [comment]
The latest version of SlowCheetah does not offer support for VS 2012/2013 but the last release of the previous version does, which you can find [here](https://github.com/sayedihashimi/slow-cheetah/releases/tag/v2.5.48).
If there is demand for new features of SlowCheetah in older versions of VS, we may release versions of the package that work for them. Unfortunately, at this time, we can't support these versions all in one package.

**Comment by MassimoSporchia** [comment]
works flawlessy, thanks!
