### ISSUE TITLE
Transforms don't seem to work for Solution Configurations.

### ISSUE THREAD

**Issue by AlonCG** [Microsoft/slow-cheetah#46]
I have a number of solution configurations that I would like to add transforms. 

I am using the latest version of SlowCheetah (3.0.61) in an ASP.Net Core project (full DotNet framework). While the "Debug" and "Release" transforms seem like they may work .. VS2017 added them and I can also preview them, none of my other Solution configurations even generate a preview.

Any suggestions?

**Update**: If I delete all my solution configurations and then add them back, with "Create New Project Configurations" checked, then this seems to work. if this is how it should be, then I think the documentation should reflect this.

**Comment by davilimap** [comment]
Can you give more information about this issue? I assume the this is a web application since you mentioned ASP.Net. What file are you trying to transform?
Can you give steps to reproduce this issue from a new project?

**Comment by AlonCG** [comment]
Yeah sure ... using Visual Studio 2017.2, 

1. Create a new Asp.Net Core Web Application (.Net Framework, Web Application, No Auth)
2. Add new solution configurations "Debug_Local" & "Debug_Azure" (Copy from "Debug", **do not select** "Create new project configurations"
3. Delete "appsettings.Development.json" (possibly optional)
4. Install Nuget "SlowCheetah" package.
5. Right-click on the appsetings.json file and "Add Transform"
6. Only the "Debug" and "Release" transforms are added. 

I think I expect the "Debug_Azure" and "Debug_Local" transforms as well. But they are not there. 

Now if I start all over again, but **select** "Create new project configurations" then the transforms are added and they can be previewed.

**Comment by AlonCG** [comment]
I am only expecting it to work based on the following line in the "transforming_files.md" doc file:

> Selecting this option will add transform files according to your project or solution's build configurations.

**Comment by davilimap** [comment]
Thanks for pointing that part of the document out, it was not clear and I will change that.
In terms of project vs. solution configurations, if you add configurations that are only for the solution, you can see in your solution file that the solution configuration gets mapped to an existing configuration for that project (usually the one that the configuration was copied from).
```
GlobalSection(ProjectConfigurationPlatforms) = postSolution
	{6E1AC444-68D1-44FE-B454-6BE9F8C86A48}.Debug_Azure|Any CPU.ActiveCfg = Debug|Any CPU
	{6E1AC444-68D1-44FE-B454-6BE9F8C86A48}.Debug_Azure|Any CPU.Build.0 = Debug|Any CPU
EndGlobalSection
```
This means that the project doesn't actually recognize the solution configurations and will just behave as if the mapped configuration was being used. If you want your configuration to generate different transformations, I recommend creating that configuration for the project as well.

**Comment by AlonCG** [comment]
Yeah ... I did create project configurations as well so it would work. Thanks!
