### ISSUE TITLE
SlowCheetah Task not compatible with .NET CLI

### ISSUE THREAD

**Issue by AlonCG** [Microsoft/slow-cheetah#48]
In an attempt to update my EF Core first database ... I run `dotnet ef database update`.

This results in the following error:

> C:\Users\Alon\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\Microsoft.VisualStudio.SlowCheetah.targets(83,5): error MSB4062: The "TransformTask" task could not be loaded from the assembly C:\Users\Alon\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\..\tools\Microsoft.VisualStudio.SlowCheetah.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Others are experiencing this same exact issue ... from [SO](https://stackoverflow.com/questions/44140052/dotnet-build-fails-but-building-works-in-visual-studio-slowcheetah).

Any chance this project is being bit by the same thing that the SO [mentions](https://github.com/dotnet/cli/issues/5457)?

"DotNet" commands worked no problem before installing SlowCheetah. Any suggestions? (Which would also help the OP in the SO issue as well!)

**Comment by davilimap** [comment]
It seems the problem here is that the path to the DLL was incorrectly built. There should be a backslash right after the `build` and before `..`. [Here](https://github.com/Microsoft/slow-cheetah/blob/master/src/Microsoft.VisualStudio.SlowCheetah/Build/Microsoft.VisualStudio.SlowCheetah.targets#L16) is the line in the targets that we use to build the path. [This](https://msdn.microsoft.com/en-us/library/ms164309.aspx) states that `MSBuildThisFileDirectory` should include the final backslash. This seems to be a problem with .NET CLI breaking this property.

**Comment by AlonCG** [comment]
Thanks @davilimap for the explanation ... do I need to wait for the cli to be updated? Is there anything I should be doing to move forward? (clone repo, make changes, figure how to use those changes in my project, etc)?

And thanks for all the work you have done on this.

**Comment by davilimap** [comment]
I've been investigating this issue a bit more, haven't been able to reproduce it so far. A possible workaround would be to go into the SlowCheetah target file and edit the `<SlowCheetahTaskPath>`, adding a backslash after `$(MSBuildThisFileDirectory)`.
If this is possible, could you try it and see if it works? That would help me to better identify the problem

**Comment by tpodolak** [comment]
Hi 
I've encountered similar issue as @AlonCG. Running ``dotnet build`` results in following message

> C:\Users\Tomek\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\Microsoft.VisualStudio.SlowCheetah.targets(83,5): error MSB4062: The "TransformTask" task could not be loaded from the assembly C:\Users\Tomek\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\..\tools\Microsoft.VisualStudio.SlowCheetah.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\Tomek\Documents\Visual Studio 2017\Projects\JsonTrasforms\JsonTrasforms\JsonTrasforms.csproj]

If you take a closer look at the error message you will notice that the path to SlowCheetah's targets is

` C:\Users\Tomek\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\..\tools\Microsoft.VisualStudio.SlowCheetah.dll`

As you can see all the backslashes are on place however it seems that `..` syntax is not resolved as the parent directory. I've tried your suggestion @davilimap, however, adding additional backslash to `SlowCheetahTaskPath` didn't help - path was resolved as 
`C:\Users\Tomek\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\\..\tools\Microsoft.VisualStudio.SlowCheetah.dll`.

**Comment by tgobena** [comment]
Does this work for .net core? I added the hard code path for the SlowCheetahTaskPath path in the Microsoft.VisualStudio.SlowCheetah.App.targets file and I am seeing the following error from the command line. It is building fine in visual studio. I am getting error when I run it from command "dotnet publish --framework net462 --output "PACKAGE" --configuration Release"
Error:

C:\Users\[user]\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\Microsoft.VisualStudio.SlowCheetah.App.targets(63,5): error MSB4062: The "TransformTask" task could not be loaded from the assembly C:\Users\[user]\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\tools\Microsoft.VisualStudio.SlowCheetah.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

**Comment by davilimap** [comment]
I've done some more investigating of this issue and it seems like I was mistaken with my original assessment of the problem being with backslashes (which was why I originally asked if adding it would fix the problem). That is also why I wasn't able to reproduce it.
The problem seems to be what is stated [here](https://github.com/dotnet/cli/issues/5457#issuecomment-275222952) and [here](https://github.com/Microsoft/msbuild/issues/2111) where the .NET CLI doesn't have  the same framework loaded as MSBuild, so it doesn't recognize the task. The fix on our side for this is to multitarget the task based on the framework. I'll add this to the issue concerning compatibility with .NET core. I'm unsure if there's a fix on your side that can be used right now, but if I find one, I'll post it here.

**Comment by johnmurphy01** [comment]
I'm running a .NET 4.5 console application and I'm having the same issue. I originally was using the SlowCheetah VS Extension(VSIX) but decided to move to the NuGet package(2.5.48). I installed the NuGet package, uninstalled and Extension and I'm getting the same error as @AlonCG posted.

When I go to the packages folder for SlowCheetah, the DLL file name is `SlowCheetah.dll` and not `Microsoft.VisualStudio.SlowCheetah.dll`. That makes sense why it can't find the dll. I renamed the dll but the `TransformTask` task still cannot be loaded from the assembly. 

I really need the ability to perform transforms on my App.config file via MSBuild. Hopefully this will be resolved soon.

**Comment by johnmurphy01** [comment]
Turns out there's a Nuget package for SlowCheetah _and_ Microsoft.VisualStudio.SlowCheetah. I had them both installed it appears. Removed both and re-installed Microsoft.VisualStudio.SlowCheetah and my local project is building.

**Comment by jviau** [comment]
Yes, sorry about that @johnmurphy01. We renamed the packages and vsix to show that Microsoft has officially taken over this project.

**Comment by dozer75** [comment]
What's the status for this one? I am using the Microsoft.VisualStudio.SlowCeetah package, but get the error as described by others. Since mbuild deployment doesn't work with runtime identifiers the only option is to use the dotnet cli commands, but this issue is blocking that workaround.

**Comment by mattfrear** [comment]
It doesn't work for me either. I have a solution which has both .NET Standard and .NET Framework projects in it - the .NET Framework ones are using SlowCheetah to transform my app.config.
When I `dotnet build` I see
```
Executing: "C:/Program Files/dotnet/dotnet.exe" build "Promotions.Management.sln" --configuration Release
/p:Version=1.0.2-local
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

C:\code\vsts\Backlog\commerce-promotions-management\packages\Microsoft.VisualStudio.SlowCheetah.3.0.61\build\Microsoft.VisualStudio.SlowCheetah.App.targets(63,5): error MSB4062: The "TransformTask" task could not be loaded from the assembly C:\code\vsts\Backlog\commerce-promotions-management\packages\Microsoft.VisualStudio.SlowCheetah.3.0.61\build\..\tools\Microsoft.VisualStudio.SlowCheetah.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\code\vsts\Backlog\commerce-promotions-management\test\Management.FunctionalTests\Management.FunctionalTests.csproj]
```

**Comment by moffatdm** [comment]
Many thanks for fixing this. Do you have an ETA as to when the next version that includes this fix will be pushed to NuGet?

**Comment by AHoran** [comment]
2 months have passed since the apparent fix was merged. Any ETA on moving to nuget?

**Comment by MarienMonnier** [comment]
I stumbled upon this issue while searching for the [same issue](https://github.com/madskristensen/WebCompiler/issues/321) but with another product, while building on VSTS (with `dotnet publish`, so not exactly the same case).
I don't know if this will help, but I succeeded in building my project by adding the Microsoft.Build.Utilities.Core nuget package to my .csproj file:
`<PackageReference Include="Microsoft.Build.Utilities.Core" Version="15.5.180" />`

**Comment by martinoss** [comment]
@MarienMonnier Did this help in conjunction with SlowCheetah? For me it does not help...

**Comment by MarienMonnier** [comment]
@martinoss Sorry, as I told before, this was not linked to SlowCheetah. This issue was one of the few that I found with the same error as I had, and I thought maybe it could help...

**Comment by maxisam** [comment]
FYI @MarienMonnier 's solution doesn't work.

**Comment by jonathh21** [comment]
I too have hit this apparent issue..

note the presence of the '\2.5.48\build\**..**\tools\'

The "TransformTask" task could not be loaded from the assembly C:\Users\<user>\.nuget\packages\slowcheetah\2.5.48\build\..\tools\Microsoft.VisualStudio.SlowCheetah.dll. Could not load file or assembly 'file:///C:\Users\<user>\.nuget\packages\slowcheetah\2.5.48\tools\Microsoft.VisualStudio.SlowCheetah.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	InboundIntegrationPlatform	C:\Users\<user>\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\Microsoft.VisualStudio.SlowCheetah.App.target	

I'm going to try removing everything (again)..

**Comment by jonathh21** [comment]
I can report that the tip about Microsoft.VisualStudio.SlowCheetah vs (the more downloaded) SlowCheetah has paid dividends.

once I removed both of these and re-added just the Microsoft one it seemed ok.

**Comment by Wheater** [comment]
Is there an update to this? The relative path is still appearing in the output for me: "build\..\tools". I need a solution as soon as possible and the other options in this thread have not worked for me.

**Comment by mjurca** [comment]
Try adding package version: 3.1.61-pre
https://www.nuget.org/packages/Microsoft.VisualStudio.SlowCheetah/3.1.61-pre

**Comment by jonathh21** [comment]
Hi guys,

Much time has past - and we are/were having issues with these pesky transforms, that is actually getting them to transform at all on core projects.

Just installed the 3.1.61-pre and it fixes our json and xml woo's - however it doesn't seem to apply the publish profile transform - only the config name (eg .debug./.release.).

So before .publishprofilename.config/xml would be considered for a transform and it seems to not be now.


Also had an issue whereby it was caching/using a .previous config transform in /obj/ after I'd completely removed the .debug.config transform. Had to manually delete this file.

Anyone else experiencing this/these?

**Comment by daghb** [comment]
3.1.61-pre immediately fixed my problem. Thanks.

**Comment by davilimap** [comment]
@jonathh21 The caching is due to the new behavior introduced in version [3.1.61-pre](https://github.com/Microsoft/slow-cheetah/releases/tag/v3.1.61-pre). I think transforming despite the transform file being deleted could be a separate bug.
Can you try building/publishing your project with logging enabled (for example, running `msbuild /t:Publish /v:diag`) and checking for the SlowCheetah targets (ScApplyTransforms and ScApplyWebTransforms)?

**Comment by GenBurnside** [comment]
I was getting the original ``error MSB4062: The "TransformTask" task could not be loaded from the assembly...`` in a large solution with both SlowCheetah 2.5.48 and Microsoft.VisualStudio.SlowCheetah 3.1.66 referenced across different projects. Building the solution with VS2017 would work fine, but running ``dotnet build -c Release`` or ``dotnet publish -c Release`` on a specific netcore csproj resulted in the error. 

After removing SlowCheetah 2.5.48 and replacing with the MS-maintained 3.166 version, the error was resolved.
