### ISSUE TITLE
File to transform not found / wwwroot folder / ASP.NET Core 1.1 

### ISSUE THREAD

**Issue by martinoss** [Microsoft/slow-cheetah#57]
I wanted to add an environment.json for my SPA to be transformed on build/publish.
It works for the root directory but not if the json is inside the wwwroot folder.
As soon as I add transforms to my json file, building/publishing fails with error:
Severity	Code	Description	Project	File	Line	Suppression State

> Error	MSB4018	The "SlowCheetah.TransformTask" task failed unexpectedly.
> 
> System.IO.FileNotFoundException: File to transform not found
> File name: 'D:\myproject\wwwroot\enviroment.json;D:\myproject\wwwroot\enviroment.json'
>    at Microsoft.VisualStudio.SlowCheetah.JsonTransformer.Transform(String source, String transform, String destination)
>    at Microsoft.VisualStudio.SlowCheetah.TransformTask.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyProject	C:\...\.nuget\packages\microsoft.visualstudio.slowcheetah\3.0.61\build\Microsoft.VisualStudio.SlowCheetah.targets	83	

Looks like the same file appears to times in the path.

**Comment by jviau** [comment]
From that callstack the file name looks weird: `D:\myproject\wwwroot\enviroment.json;D:\myproject\wwwroot\enviroment.json` Does your project file have that exact string in it?

**Comment by martinoss** [comment]
The project file looks like this (just reproduced it in a new project):

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\environment.Debug.json">
      <IsTransformFile>True</IsTransformFile>
    </None>
    <Content Include="wwwroot\environment.json" />
    <None Include="wwwroot\environment.Release.json">
      <IsTransformFile>True</IsTransformFile>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.SlowCheetah" Version="3.0.61" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot/environment.json">
      <TransformOnBuild>true</TransformOnBuild>
    </Content>
  </ItemGroup>

</Project>
`

**Comment by jviau** [comment]
.netcore projects already include all items via glob, so this may be due to msbuild items being duplicated. Can you try changing to:

``` xml
<Content Update="wwwroot/environment.json">
  <TransformOnBuild>true</TransformOnBuild>
</Content>
<Content Update="wwwroot\environment.Debug.json">
  <IsTransformFile>True</IsTransformFile>
</Content>
<Content Update="wwwroot\environment.Release.json">
  <IsTransformFile>True</IsTransformFile>
</Content>
```

Remove the `None Includes` and the `Content Include`. Also, the contents of the `wwwroot` folder _may_ be copied to the output directory by default, if that is the case and it runs _after_ slow cheetah, that copy will overwrite the transform. If that happens you want to find those items in the solution explorer and set copy to output "never"

**Comment by jviau** [comment]
Closing for now. Re-open if my last reply did not solve your issue.
