### ISSUE TITLE
Improve title on github

### ISSUE THREAD

**Issue by sayedihashimi** [Microsoft/slow-cheetah#58]
The title is currently set to:

>  Tooling for file transforms on build and in Visual Studio

I think better would be:

Tooling for xml and json file transforms on build from Visual Studio and MSBuild.

The current text makes it seem like you need to use Visual Studio for the transforms to be executed.

**Comment by davilimap** [comment]
I like this title better too. Thanks Sayed!

**Comment by sayedihashimi** [comment]
Thanks for updating it.
