### ISSUE TITLE
ApplicationSettings Transforms Are Ignored

### ISSUE THREAD

**Issue by dlee1964** [Microsoft/slow-cheetah#69]
Using VS 2015, transformations for application settings within the application settings group and inside the (projectname).Properties.Settings group are ignored.   The transforms preview fine, but clearly are ignored in the test environment.  This is in version 3.0.61.18192. 

My application code which accesses the setting is as follows:

`                                rpvNoticeDocument.ReportPath = NoticesCommon.Properties.Settings.Default.CobraHeader;`

The setting is essentially a path to an rdlc file which differs between debug and test environments, and the setting is located in a "common" project, which is other than where the code that accesses it exists.  If the tranformation is bypassed and the test environment path is inserted into the setting prior to building the test executable, the application finds the rdlc no problem, proving the issue is with the transform.

**Comment by jviau** [comment]
See my comment on your other issue, #68. Closing in favor of that one.
