### ISSUE TITLE
Error : "Data at the root level is invalid. Line 1, position 1."

### ISSUE THREAD

**Issue by buaziz** [Microsoft/slow-cheetah#70]
am running on .NET core and i keep getting this error on all json transforms

**Comment by jviau** [comment]
Can you share examples of what your source and transform json file look like?

**Comment by phillijw** [comment]
It's likely because you have invalid xml

**Comment by jviau** [comment]
Closing due to no response. Re-open if you need more assistance.

**Comment by bryanparke** [comment]
I'm also having this issue, it is with any .json file that I attempt to preview the transform.  Here is the sample input json

`{
    "A" : {
        "A1" : "11"
    },
    "B" : {
        "1B" : 12,
        "2B" : 22
    },
    "C" : {
        "C1" : 31,
        "C2" : 32
    }
}`

No matter what, when I choose to preview the transform, the error is always "Data at the root level is invalid. Line 1, position 1."

**Comment by phillijw** [comment]
json files are not xml files. The error you're receiving is from an xml parser.

**Comment by bryanparke** [comment]
Hi Joe, I understand that xml and json files are different. In this case I’m using json configuration files. Slow-cheetah supports json and xml, correct? I built the transforms using the extension and I am just trying to use the built-in preview function to test my transforms.

Bryan Parke
Noble Software Group LLC
Programmer
office (530) 605-2650
cell (530) 945-8124
http://www.noblesg.com
________________________________

**Comment by mwpowellhtx** [comment]
Just using _SlowCheetah_ in my project and receiving a similar issue. I have a couple of issues.

1. Using _Add Transforms_ menu options, complaining that my package was up to date. I added _SlowCheetah_ package to my `Directory.Build.props` as a boilerplate package I wanted to add. Instead I added directly to my csproj. Verified also package version is the latest. That aside...

1. asd

My `appsettings.json` file something like this:

```json
{
    "Testing": {
        "Value": 1
    },
    "TestingArray": [
        { "Value": 1 },
        { "Value": 2 },
        { "Value": 99 }
    ],
    "Twitter": {
        "authorizations": [
            {
                "name": "bearerDefault",
                "authorizationtype": "bearer",
                "token": "123"
            },
            {
                "name": "accessDefault",
                "authorizationtype": "access",
                "token": "345",
                "tokensecret": "567"
            }
        ]
    }
}
```

Obviously these are boilerplate values, transforms added in `Debug` and `Release` configurations.

The error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Data at the root level is invalid. Line 1, position 1.	...Twitter.Client.Tests	E:\Dev\NuGet\global\packages\slowcheetah\2.5.48\build\SlowCheetah.targets	192	
```

In either transform, nothing being transformed, yet, literally:

```json
{
}
```

As far as I understand it, SC does also support json transformation, correct? IIRC, when last I checked, with a [document transforms](https://github.com/Microsoft/json-document-transforms) dependency.

But this is an error? How?

**Comment by mwpowellhtx** [comment]
I see I see... I cleaned the project output and rebuild. Then no errors. Cheers 🍻
