### ISSUE TITLE
.NET 4.5 MSBuild Transforms not working

### ISSUE THREAD

**Issue by johnmurphy01** [Microsoft/slow-cheetah#71]
I have version `3.0.61` installed via Nuget.

My project is a .NET 4.5 Console Application(using Visual Studio 2015) and I want to transform my App.config file. I have created the transforms

![image](https://user-images.githubusercontent.com/2939548/29177786-3d7007ac-7db5-11e7-849f-00383e04ccbd.png)

In the `.csproj` file, I see that the markup necessary to get SlowCheetah to work is present(although there are warnings about invalid child elements for `TransformOnBuild` and `IsTransformFile`:

![image](https://user-images.githubusercontent.com/2939548/29177826-625c3932-7db5-11e7-8671-d26f313e3208.png)

I see that the target for SlowCheetah is referenced:

![image](https://user-images.githubusercontent.com/2939548/29177896-91528a70-7db5-11e7-9fd5-93e5cd63cbe1.png)

But, when I build my project, for example in Release configuration, my transforms were not applied. In the output window, I do not see any reference to the fact that SlowCheetah is even trying to run, making me think that the Tasks are just not running and/or aren't being referenced.

Ultimately, I want to be able to run MSBuild during my Continuous Integration process and have the transforms apply appropriately.

**Comment by jviau** [comment]
You can ignore the xml warnings - Visual Studio editor has an xsd for msbuild, but it only contains a limited set of items. MSBuild xml ultimately has no defined schema for properties and item metadata.

I believe the issue is slow-cheetah _is_ running, but app.config is then being copied to the output directory and undoing the transform. Can you remove this line and try again:

`` xml
<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
``

**Comment by johnmurphy01** [comment]
I removed the above line but now there is no `App.config` at all in my Release folder. In Visual Studio, the Copy to Output Directory option is now set to `Do not copy`

**Comment by johnmurphy01** [comment]
Ok, more info. I turned on Detailed verbosity for MSBuild. 

The `App.config` file is successfully transformed into `obj\Release\MyProject.csproj-sc.App.config`

However, further down, the -sc.App.config file is then copied into `bin\Release\MyProject.exe.config`. I am guessing that having an `App.config` _and_ the `MyPrjoect.exe.config` was causing problems? Possibly the application was reading the `App.config` file instead of the `MyProject.exe.config` file? I'm not super familiar with the whole `app.config` ecosystem, so this is just a speculation.

**Comment by johnmurphy01** [comment]
I believe this can be closed now, the issue I _think_ was as @jviau pointed out and the app was looking at the copied `App.config` and not the transformed `.exe.config` file.

**Comment by jviau** [comment]
@johnmurphy01 sorry, I completely missed that this was an app.config file. You are correct, app.configs are transformed to `.exe.config` or `.dll.config`. Maybe having a separate `app.config` does cause confusion? I am not sure about that though, never tried it myself.
