### ISSUE TITLE
'Add Transform' context menu item missing for console application in VS2017

### ISSUE THREAD

**Issue by robbell** [Microsoft/slow-cheetah#74]
I have a .NET 4.6.1 console application in VS2017 Enterprise which doesn't show the 'Add Transform' context menu for the App.config after installing both the VS extension and the NuGet package.

![image](https://user-images.githubusercontent.com/44835/29561969-6b114d3c-872f-11e7-9046-e108ce8bb711.png)

**Comment by sitty** [comment]
I'm having the same issue as well on VS 2017 15.3.2

**Comment by davilimap** [comment]
Does this happen with just a new console app? Does the Add Transform option show up for other files in the project?

**Comment by myrklewk** [comment]
I'm also having this problem. Also happens with a new console app. "Add Transform" doesn't show up for other files in the project either. VS 2017 15.6.5 and 15.6.7 (upgraded to see if that fixed things).

**Comment by myrklewk** [comment]
For my case it was just me not RTFM. I had installed the nuget package but not the extension.

**Comment by motek80** [comment]
Had the same issue. I found that in case SlowCheetah installed via Nuget - there is an issue with missing "Add  Transform" menu item. However, in case SlowCheetah installed via Tools --> Extensions\Updates - everything is work as expected.

**Comment by davilimap** [comment]
We'll consider updating the main page to make it more clear that the extension is necessary for context menus and the nuget package is only for build-time logic.
Meanwhile, I'll close this issue. If anyone is still having problems with the extension, you can reopen this, ideally with repro steps for the issue.

**Comment by nbenninghoff** [comment]
> We'll consider updating the main page to make it more clear that the extension is necessary for context menus and the nuget package is only for build-time logic.

Please put this first, as the wording on this page directly conflicts:
https://marketplace.visualstudio.com/items?itemName=vscps.SlowCheetah-XMLTransforms

"Getting started is really simple, just install this package. Then in the solution explorer you can easily add your config transform by right-clicking and selecting Add Transform."

False!

**Comment by minhtien020900** [comment]
> Had the same issue. I found that in case SlowCheetah installed via Nuget - there is an issue with missing "Add Transform" menu item. However, in case SlowCheetah installed via Tools --> Extensions\Updates - everything is work as expected.

thank sir, it works. Step details:
: ![Image](https://github.com/user-attachments/assets/f939eb2b-9db6-478c-a35a-0fcc8aa8882a)

![Image](https://github.com/user-attachments/assets/430aa130-c9e7-4a8f-b1ad-87ffafe090f3)

Here's the English translation:

"Then close Visual Studio to allow the installer to proceed. And enjoy!" 
![Image](https://github.com/user-attachments/assets/4f8bc81d-3c6e-4350-bdc2-a97358a89bd7)
