### ISSUE TITLE
Transformations from referenced project aren't applied

### ISSUE THREAD

**Issue by Vrlwrox** [Microsoft/slow-cheetah#75]
When a project references another one that contains a normal XML file and its transformations the transformed XML file from referenced project is not copied to the output of project referencing it (note that transformations are applied and copied to output folder of their project).

I noticed a property ScAllowReferencedConfig mentioned in [documentation](https://github.com/Microsoft/slow-cheetah/blob/master/doc/targets.md) that seems to indicate this is possible. Although I cannot find any references to this property anywhere in code.

Version 3.0.61, Visual Studio 2017

**Comment by deceptiveSimplicity** [comment]
Same problem here.

**Comment by davilimap** [comment]
As the documentation states, the `ScAllowReferencedConfig` property is for config files, which get copied over correctly.

Regular XML files need to be set as "Copy to output directory" to be copied over to referencing projects. Unfortunately, in my testing the file copied over is not the transformed one. I'll change the name of the issue to reflect this bug.
