### ISSUE TITLE
Which package is the correct one

### ISSUE THREAD

**Issue by pekkah** [Microsoft/slow-cheetah#80]
There are multiple  SlowCheetah packages in NuGet. Which one should I install? What is the latest and the greatest.

**Comment by jviau** [comment]
Thanks for pointing this out, I realized some of our links are broken. I have updated the one on the Releases. I'll fix the others and make the readme more clear on what to install as well.

To answer directly, here are the links:
VSIX for optional tools: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.SlowCheetah-XMLTransforms
Nuget package for transform on build: https://www.nuget.org/packages/Microsoft.VisualStudio.SlowCheetah

**Comment by sgrips** [comment]
not work for VS2017 build debug and relase not apply anything change to file...
