### ISSUE TITLE
Preview Transform not working for publish profile transform

### ISSUE THREAD

**Issue by sanddigital** [Microsoft/slow-cheetah#82]
Hi, 

If I right-click on a Publish Profile transform file (e.g. appSettings.CustomProfile.json) and select Preview Transform, nothing happens.

![image](https://user-images.githubusercontent.com/1873105/30679907-f4fe1404-9edf-11e7-861d-ae8d8d69c38e.png)

Previewing transforms for build configuration files (Debug/Release) works fine.

This is for a AspNetCore 2.0 project.

Thanks

**Comment by davilimap** [comment]
As I commented in #101, this issue is the same as #98 with the caveat of publish profiles not being recognized on the extension. Closing in favor of other issues.
