### ISSUE TITLE
Inconsistent line endings on generated transformation files

### ISSUE THREAD

**Issue by davilimap** [Microsoft/slow-cheetah#9]
Newly-generated files have inconsistent line endings causing the following message to appear on opening the files:
![image](https://cloud.githubusercontent.com/assets/11531010/25399784/6aa20400-29a5-11e7-8f84-c4b94f674f5e.png)
The generated files should have consistent line endings without requiring input from the user to change them.

**Comment by jviau** [comment]
I believe this is fixed now.
