### ISSUE TITLE
Preview Transform does not work unless you have associated project configurations

### ISSUE THREAD

**Issue by mhenry1384** [Microsoft/slow-cheetah#98]
For reasons to boring to explain, I have a transformations that do not have associated project configurations.  For example, though I only have "Debug" and "Release" configurations, I might have an app.config transformation named "Foo.Bar.exe.Production.config"
```

    <Content Include="Foo.Bar.exe.Production.config">
      <DependentUpon>App.config</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
      <IsTransformFile>True</IsTransformFile>
    </Content>
```

This has always worked in the past, but isn't working for me now
Visual Studio 2017 15.4.5
SlowCheetah 3.0.61.18192

When I try to preview my transform files, nothing happens.  I don't even get a preview window.  Again, this used to work.  :-(

**Comment by bryanparke** [comment]
FYI, I was also having this issue but then I noticed there are 2 "Preview Transform" options in the context menu.  The top one (the one that has the icon next to it) does nothing, the second one (about half way down the context menu for me) does attempt to show the preview.

![image](https://user-images.githubusercontent.com/36426855/36126477-78c9a4b2-100d-11e8-8c9f-bf9c20ad49b7.png)

**Comment by mhenry1384** [comment]
@bryanparke Thanks that works.

**Comment by rawk01** [comment]
Hmm I have exactly the same problem, however I only get the first menu item.

It works fine on my web project, but not on my class libraries (which all have slow cheetah configs)

This was working previously (studio 2015 though).

**Comment by mhenry1384** [comment]
I put up a PowerShell script that will transform all the configs in a solution. May be useful if you can't get SlowCheetah to work:  https://github.com/mhenry1384/ValidateTransforms

**Comment by rawk01** [comment]
Thanks ^^ that will be useful for the build anyway

**Comment by icnocop** [comment]
The [v2.5.48 release notes](https://github.com/sayedihashimi/slow-cheetah/releases/tag/v2.5.48) indicate that you have to manually uninstall the old version of SlowCheetah.

Would not uninstalling the old version cause the issue where you'd see two "Preview Transform" menu items?
